/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package boffin;
import java.util.Scanner;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
        Scanner inputScanner = new Scanner(System.in);

        System.out.println("Who is your favorite TA at Wright state");
        String answer = inputScanner.next();

        System.out.println("Your answer was " + answer);

        inputScanner.close();
    }
}
